from pathlib import Path
common_style='''
:root{--bg:#000;--fg:#fff;--hair:rgba(255,255,255,.08);--accent:#023548;--max:1000px;--sans:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;}
*{box-sizing:border-box} body{margin:0;background:var(--bg);color:var(--fg);font-family:var(--sans);-webkit-font-smoothing:antialiased;} a{color:inherit;text-decoration:none}
header{position:sticky;top:0;z-index:100;background:rgba(0,0,0,.82);backdrop-filter:blur(10px);border-bottom:1px solid var(--hair);padding:8px 0;}
.nav{max-width:var(--max);margin:auto;padding:0 18px;display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap;}
.logo{font-size:12px;letter-spacing:.3em;opacity:.7}.logo:hover{opacity:1}.links{display:flex;gap:10px;flex-wrap:wrap}
.pill{border:1px solid rgba(2,53,72,.7);background:rgba(2,53,72,.15);padding:9px 12px;border-radius:14px;font-size:10px;letter-spacing:.25em;text-transform:uppercase;transition:.18s}
.pill:hover{background:rgba(2,53,72,.28);border-color:rgba(2,53,72,1);transform:translateY(-1px)}
.wrap{max-width:var(--max);margin:auto;padding:60px 22px 100px} h1{margin:0 0 24px;font-size:clamp(42px,7vw,72px);letter-spacing:.06em;text-transform:uppercase}
.heroImg{width:min(100%,560px);aspect-ratio:4/5;object-fit:cover;border-radius:22px;margin:0 0 28px;display:block}
.statement{font-size:clamp(17px,1.9vw,21px);line-height:1.75;opacity:.9;max-width:840px;margin-bottom:64px;white-space:pre-line}
.sectionTitle{font-size:12px;letter-spacing:.32em;text-transform:uppercase;opacity:.6;margin:42px 0 20px}.project{border-top:1px solid var(--hair);padding:20px 0}
.projectTitle{font-size:20px;margin-bottom:6px}.projectMeta{font-size:12px;letter-spacing:.18em;text-transform:uppercase;opacity:.72;margin-bottom:14px;color:var(--accent)}
.projectDesc{opacity:.78;line-height:1.75;white-space:pre-line}.projectDesc p{margin:0 0 14px}.ext{font-size:13px;letter-spacing:.12em;text-transform:uppercase;opacity:.82;color:var(--accent)}
footer{margin-top:80px;font-size:11px;letter-spacing:.2em;opacity:.5;text-transform:uppercase}@media (max-width:700px){.heroImg{width:min(100%,420px)}.links{gap:8px}.pill{font-size:9px;padding:8px 10px}}
'''

def mk(title,img,nav,statement,sections):
    links=''.join([f'<a class="pill" href="{h}">{l}</a>' for h,l in nav])
    return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — Malia Taylor</title><style>{common_style}</style></head><body><header><div class="nav"><a class="logo" href="index.html">MALIA TAYLOR</a><div class="links">{links}</div></div></header><div class="wrap"><h1>{title}</h1><img class="heroImg" src="images/{img}" alt="{title} image"><p class="statement">{statement}</p>{sections}<footer>Malia Taylor</footer></div></body></html>'

pages = {
'writer.html': mk('Writer','writer.jpg',[('producer.html','Producer'),('intimacy.html','Intimacy'),('mystic.html','Mystic'),('healer.html','Healer'),('rebel.html','Rebel'),('index.html#contact','Contact')],"""Malia's writing focuses on overcoming challenges that lead to personal transformation.

She writes character-driven stories, amplifying female voices, queer identity, and caretaking — often using humor, intimacy and illness, to explore, themes of grief, joy and belonging within the authentic human experience.""","""
<div class="sectionTitle">Projects</div>
<div class="project"><div class="projectTitle">A Field Full of Wishes</div><div class="projectMeta">Script | Movie (Drama, Biography)</div></div>
<div class="project"><div class="projectTitle">The Divine Madman</div><div class="projectMeta">Script | Movie (Dramedy)</div></div>
<div class="project"><div class="projectTitle">In Silence</div><div class="projectMeta">Pre-Production | Short</div></div>
<div class="project"><div class="projectTitle">Mrs. Claus Has Menopause : A Midlife Christmas Carol</div><div class="projectMeta">Scriptment | Movie, Musical (Family, Holiday, Comedy)</div></div>
<div class="project"><div class="projectTitle">Mrs. Claus Has Menopause 2: The Snow Maiden</div><div class="projectMeta">Treatment | Movie (Family, Holiday, Drama)</div></div>
<div class="project"><div class="projectTitle">Blue Butterfly Zone</div><div class="projectMeta">Pitch | Movie or Series (Political Drama, Supernatural, IP)</div></div>
<div class="project"><div class="projectTitle">Phantastes [IP]</div><div class="projectMeta">Pilot | Series (Animation or Live Capture, Fantasy, Family)</div></div>
<div class="project"><div class="projectTitle">Embracing Mercy</div><div class="projectMeta">Script | Movie (Rom Com)</div><div class="projectDesc"><p>When Mercy Whitman, a quirky twenty-something who eschewed the Ivy League for Massage School, discovers an inner Voice trying to guide her every move, her world is turned upside-down. This is only compounded after meeting Stanner Collins, a famous but broken musician who can't quite understand what sparked their connection.</p><p>A twenty-something, free-spirit who ditches East Coast Ivy League for West Coast Massage School falls for a famous and flawed musician just as she begins hearing an Inner Voice helping to guide her path, which forces her to question whether surrendering to love and embracing your identity can coexist.</p></div></div>
<div class="project"><div class="projectTitle">Deux Date</div><div class="projectMeta">Script | Movie (Rom Dramedy)</div><div class="projectDesc"><p>Single-mom, Abby Stewart and her teenage daughter Eden are happily ensconced in their Rhode Island life until both become pregnant. Forced to navigate the highs and lows of unexpected pregnancy in a small town, learning how to open their reluctant hearts to themselves, to true love and to each other.</p></div></div>
<div class="project"><div class="projectTitle">Lost. Love [Companion*]</div><div class="projectMeta">Script | Movie (Drama)</div><div class="projectDesc"><p>Single-mom, Clare Owens, discovers her teenage son Michael has cancer. Her womanhood is tested trying to nurse him to health while a potential new love interest offers connection. She navigates a tsunami of emotions as love, vulnerability and heartache trigger disappointments from all the men in her past.</p><p>When a single mother’s teenage son is diagnosed with cancer, she must confront her own suppressed desires and past disappointments as a new romantic connection threatens to reopen wounds she’s spent a lifetime closing.</p></div></div>
<div class="project"><div class="projectTitle">High School Porno [Companion*]</div><div class="projectMeta">Script | Movie (Dark Comedy)</div><div class="projectDesc"><p>A transgender teen who's a prodigy filmmaker discovers his life-long best friend has cancer. Banding together a group of misfit friends use their creativity in unconventional ways earning fast money to help pay for life-saving treatments, but in the upheaval discover found family and the value of belonging.</p><p>When a transgender teen filmmaker’s best friend is diagnosed with cancer, he and a group of misfit classmates launch a wildly unconventional money-making scheme to fund treatment, discovering found family, creativity, and belonging along the way.</p></div></div>
<div class="project"><div class="projectTitle">Meryl's Dog</div><div class="projectMeta">Script | Movie (Coming-of-Age, Road Trip, Dog-Buddy)</div><div class="projectDesc"><p>When a 25yo, Singer/Songwriter, barista from Silverlake, still shaping their identity is tasked with driving the beloved dog of the world’s most famous actress across the country, they embark on a journey of healing, unlikely friendships, and self-discovery, finding, in the dog’s unconditional love, the acceptance they never knew they needed.</p><p>When a 25-year-old queer singer-songwriter stuck in Silver Lake is hired to drive the beloved dog of the world’s most famous actress across the country, the unexpected road trip forces them to confront identity, grief, and the courage to finally claim their own voice.</p></div></div>
<div class="project"><div class="projectTitle">Book of James</div><div class="projectMeta">Script | Short (Comedy)</div></div>
<div class="project"><div class="projectTitle">In Silence</div><div class="projectMeta">Pitch | Movie (Drama, Family)</div><div class="projectDesc"><p>An aspiring actress and her dying grandfather explore their family’s silent film legacy, uncovering Hollywood’s forgotten roots, rekindling the magic that shaped the city and their lives.</p><p>As her grandfather nears the end of his life, an aspiring actress uncovers her family’s forgotten silent film legacy, reconnecting with the roots of Hollywood and the unspoken bonds that shaped them both.</p></div></div>
<div class="project"><div class="projectTitle">In Silence</div><div class="projectMeta">Short | Drama</div><div class="projectDesc"><p>In the hours leading to his passing, Sophia makes a connection that goes beyond words, caring for her ailing grandfather til he takes his final breath.</p><p>In the final hours of her grandfather’s life, a young woman forms a connection that transcends words, discovering intimacy and legacy in silence.</p></div></div>
<div class="project"><div class="projectTitle">Tarot</div><div class="projectMeta">Pitch | Series (Drama)</div></div>
<div class="project"><div class="projectTitle">Sister Corita</div><div class="projectMeta">Pitch | Movie (Drama)</div></div>
<div class="project"><div class="projectTitle">Eat Me - Untitled Binge Project</div><div class="projectMeta">Pitch | Series (Workplace Comedy)</div></div>
<div class="project"><div class="projectTitle">UNTITLED \"QJ\" PROJECT</div><div class="projectMeta">Pitch | Series (Drama)</div></div>
<div class="project"><div class="projectTitle">A Field Full of Wishes</div><div class="projectMeta">Feature, Non-Fictional Narrative</div><div class="projectDesc"><p>On the brink of divorce, a young mom discovers her need for healing past trauma, through the wonder found in her daughter's eyes.</p><p>On the brink of divorce, a young mother reckons with unresolved childhood trauma when her daughter’s wonder and emotional clarity force her to face the healing she’s been avoiding.</p><p>After the death of her daughter's foster kitten cracks open a carefully managed facade, a depressed trauma scared homeschool mom in 2009 Los Angeles, relives the abuse and faith conditioning that shaped her, then risks her marriage, her community, and her sense of God itself to file for divorce and reclaim bodily autonomy, wonder and a future where her children learn a different definition of love.</p><p>250 character / 40 word: A trauma-scared, homeschool mom, relives the abuse & faith conditioning that shaped her; she must break the family facade by filing for divorce to reclaim bodily autonomy, wonder & a future where her children learn a different definition of love.</p></div></div>
<div class="project"><div class="projectTitle">The Divine Madman</div><div class="projectMeta">Feature - Dramedy</div><div class="projectDesc"><p>A disillusioned comic learns he's the reincarnation of a Bhutanese saint. Torn between destiny and autonomy, he embarks on a journey discovering love and the true meaning of freedom.</p><p>A burned-out stand-up comic’s life unravels when he’s told he is the reincarnation of a revered Bhutanese saint, forcing him to choose between spiritual destiny and the messy freedom of human connection.</p></div></div>
<div class="project"><div class="projectTitle">Zombie Mommy</div><div class="projectMeta">Feature - Family, Holiday, Horror-Comedy</div><div class="projectDesc"><p><span class="ext">Commercial:</span> On the eve of Halloween, a newly single mother of two is infected and begins turning into a zombie, forcing her kids to race against a spreading outbreak in their small town to save her before it’s too late.</p><p><span class="ext">Elevated:</span> When a grieving single mother is infected on the eve of Halloween and begins turning into a zombie, her children must help her resist both a spreading outbreak and her own pull toward death, proving that maternal instinct may be stronger than despair.</p><p><span class="ext">Verbal Pitch:</span> Zombie Mommy is an elevated horror-comedy about a newly single mother of two who’s infected on the eve of Halloween and begins turning into a zombie. As an outbreak spreads through their small town, her kids realize the infection is tied to her unresolved grief over a child she lost years earlier. The movie becomes a race against time, not just to stop the virus, but to help their mother choose life again. Tonally, it’s heartfelt, scary, and darkly funny, genre fun with an emotional core about motherhood, depression, and survival.</p><p><span class="ext">Button:</span> It’s a genre film where the real monster isn’t the infection, it’s grief.</p></div></div>
"""),
'producer.html': mk('Producer','producer.jpg',[('writer.html','Writer'),('intimacy.html','Intimacy'),('mystic.html','Mystic'),('healer.html','Healer'),('rebel.html','Rebel'),('index.html#contact','Contact')],"""As a Producer, Malia loves collaborating creatively to find solutions to the never-ending array of opportunities that arise everyday on sets large and small. Her years as a scrappy, single, mom of four kids tirelessly making magic happen wearing all the hats fueled by love, grit and grace are what forged in her this drive and determination. She came to believe that no matter the circumstance she found her self in, she would have faith that everything would be alright as she did everything in her power to provide the best she could to allow her children to pursue their passions in the arts. Afterall, as J.M. Barre said, \"All the world is made of faith and trust and pixie dust.\" Isn't that how movies are made?""","""
<div class="sectionTitle">Selected Projects</div>
<div class="project"><div class="projectTitle">Birthday Bird</div><div class="projectMeta">Short * 2026 * Drama</div><div class="projectDesc"><p><a class="ext" href="https://www.instagram.com/birthdaybirdshort/" target="_blank" rel="noopener">Instagram</a></p></div></div>
<div class="project"><div class="projectTitle">The Soulless</div><div class="projectMeta">Short * 2026 * Horror</div><div class="projectDesc"><p><a class="ext" href="https://www.imdb.com/title/tt37025145/?ref_=ttfc_ov_bk" target="_blank" rel="noopener">IMDb</a></p></div></div>
<div class="project"><div class="projectTitle">Different - Johnny Dawson</div><div class="projectMeta">Music Video * 2026 *</div></div>
<div class="project"><div class="projectTitle">In Silence</div><div class="projectMeta">Short | Pre-Production | Drama</div></div>
"""),
'intimacy.html': mk('Intimacy Coordinator','intimacy.jpg',[('writer.html','Writer'),('producer.html','Producer'),('mystic.html','Mystic'),('healer.html','Healer'),('rebel.html','Rebel'),('index.html#contact','Contact')],"""As an Intimacy Coordinator, I help curate the physical storytelling of intimate scenes in
Film & Television collaborating with the the creative team to bring the vision to life in a
safe and protected environment that fosters artistic freedom and curiosity. I do not shy
away from challenging stories as my passion and training is in trauma-informed and
transformational storytelling. I always look for ways to bring excellence and joy to the
work, while delivering effectively with skill and a touch of human kindness.""","""
<div class="sectionTitle">Approach</div>
<div class="project"><div class="projectTitle">Trauma-Informed Collaboration</div><div class="projectDesc"><p>Safe, protected environments that support performance, storytelling, and clear communication across cast and creative leadership.</p></div></div>
<div class="project"><div class="projectTitle">Transformational Storytelling</div><div class="projectDesc"><p>Support for challenging material with an approach rooted in artistic freedom, curiosity, and human care.</p></div></div>
<div class="project"><div class="projectTitle">Excellence With Kindness</div><div class="projectDesc"><p>A process built to deliver effectively with skill, precision, and a touch of human kindness.</p></div></div>
<div class="sectionTitle">Credentials</div>
<div class="project"><div class="projectTitle">IDC Intimacy Director and Coordinator Accelerator Program</div><div class="projectMeta">December 2025 - March 2026</div><div class="projectDesc"><p><a class="ext" href="https://www.idcprofessionals.com/" target="_blank" rel="noopener">idcprofessionals.com</a></p></div></div>
<div class="project"><div class="projectTitle">IDC Intimacy Directors & Coordinators Certification Program</div><div class="projectMeta">March 2025 - Present</div></div>
<div class="project"><div class="projectTitle">Trauma Research Foundation Certificate Program</div><div class="projectMeta">Traumatic Stress Studies Certification | March 2025 - Present</div></div>
<div class="project"><div class="projectTitle">Sex Therapy Practitioner Certification</div><div class="projectMeta">December 2025 - April 2026</div></div>
"""),
'mystic.html': mk('Mystic','mystic.jpg',[('writer.html','Writer'),('producer.html','Producer'),('intimacy.html','Intimacy'),('healer.html','Healer'),('rebel.html','Rebel'),('index.html#contact','Contact')],"""Since her early childhood Malia has had mystical experiences with the Divine. She has spent much of her life developing her inner life to learn and understand the meaning and significance of these experiences, how they have transformed her own personal story, and the impact that has had on her story among the greater human collective. Malia believes that we as humans are the bridge between the natural and the super natural world and those who are open to receiving messages can, at times, and by grace, communicate between the realms. In many ways, her healing practice, as well as her writing and work within the arts, is a mystical practice, all stemming from the artistic \"flow state\" where the Divine dances.""","""
<div class="sectionTitle">Credentials</div>
<div class="project"><div class="projectTitle">Spiritual Director</div><div class="projectMeta">Christian Formation & Direction Ministries (CFDM) | Southern California, 2012-2014</div></div>
<div class="project"><div class="projectTitle">Gordon College</div><div class="projectMeta">BA Religious Studies & Adolescent Studies | Wenham, MA, 1992-1996</div></div>
"""),
'healer.html': mk('Healer','healer.jpg',[('writer.html','Writer'),('producer.html','Producer'),('intimacy.html','Intimacy'),('mystic.html','Mystic'),('rebel.html','Rebel'),('index.html#contact','Contact')],"""After getting out of a very unhealthy relationship after 12 years of \"body anorexia\" and starving herself of physical touch and care, Malia found a home and refuge learning Massage Therapy. From there her love of the healing arts flourished as her own body began coming back to life learning how to receive non-sexual, restorative touch. Malia further deepened her somatic practice by learning everything she could about different healing modalities. She followed different paths of discovery, curious how different cultures with different language and healing practices, were all rooted in the same Divine energy to heal, and the source of Love flowing from all, was the same. Malia became a Reiki Master, a Crystal Healer, a Spiritual Healer, Teacher and Coach and continues her lifelong pursuit of the healing arts. She is an Enneagram 4 with a 5 Wing. And feels most at home when she's out of place. Her life's purpose tis to heal the world with the power of Storytelling. She is living an epic story transforming her own life, one day at a time. And finding fellow travelers along the way to swap stories and let her own stories of healing bring healing to others.

May you know that you are not broken. You are Loved. You are known. You are wanted. Yes, you can be fully known and still wanted. Exactly as you are. (Ask any one of my kids.) That is what true, Divine Love is. It's a Gift.""","""
<div class="sectionTitle">Credentials</div>
<div class="project"><div class="projectTitle">Usui Reiki Master | Healer | Teacher</div><div class="projectMeta">Hillary Faye | Laguna Niguel, California | May 2025</div></div>
<div class="project"><div class="projectTitle">Manual Lymphatic Drainage</div><div class="projectMeta">Academy of Lymphatic Drainage | July 2024</div></div>
<div class="project"><div class="projectTitle">Kundalini Reiki Master</div><div class="projectMeta">Mansions of the Heart University | Los Angeles | 2020</div></div>
<div class="project"><div class="projectTitle">Certified Healer | Teacher | Coach</div><div class="projectMeta">Mansions Of The Heart University | Los Angeles | 2020</div></div>
<div class="project"><div class="projectTitle">Certified Crystal Healer</div><div class="projectMeta">Chateau Singh Crystal Academy | 2017</div></div>
<div class="project"><div class="projectTitle">Usui Reiki Master, I, II, & III</div><div class="projectMeta">Sacred Ventures | 2015-2016</div></div>
<div class="project"><div class="projectTitle">National Holistic Institute</div><div class="projectMeta">Certified Massage Therapist | Certified Health Educator | Studio City, CA | 2010</div></div>
"""),
'rebel.html': mk('Rebel','rebel.jpg',[('writer.html','Writer'),('producer.html','Producer'),('intimacy.html','Intimacy'),('mystic.html','Mystic'),('healer.html','Healer'),('index.html#contact','Contact')],"""After a toxic mold exposure when Malia was 40, she suffered some health concerns. She had gone from extreme Whole30 Paleo to six years of being a vegan. Her weight fluctuated for years. After being diagnosed with Stage One colon cancer at the age of 48 and having emergency surgery she knew her life had become unmanageable and it was time to take back control. She tried everything she could think of on her own to no avail. Isolated and alone doomscrolling on Instagram Malia came across a woman who spoke about her own struggles and her story resonated deeply. Malia watched from the shadows as her new IG friend @Fiftyfitnessjourney spoke of the changes she made in the course of a year and the difference it made in her body. Little by little, story after story, reel by reel Malia came out of the shadows and into the light and decided to face her own reality. She was 233lbs and needed to make a change. For her family. For her health. For her future. She pulled out the work out gear and started taking walks. Denise got 10,000 steps a day, but Malia started with 3,000. Then it turned to 5,000. Before long Malia was waking up at 5:30 in the morning to get steps in and 8,000 was turning to 10,000. Every damn day. By this time, Malia wanted to make a change. She had joined Denise's Rebellion Body 12 Week Group Coaching Program for Mid-Life Women in August 2024. It included education for mindset shifting and weekly zoom calls and working with a trainer to set your macros and for periodic check ins. Progress Photos (IN A BIKINI!) and by this time Malia joined a local gym and was lifting weights four days a week. Things were shifting! Malia was learning what portions were. How much 128oz was. And what it felt like to FUEL your body. But most importantly she was doing all of this within a community of women who were in it together. Learning together. Growing together. Encouraging each other together. And showing up for themselves and one another, together.

By December, when the 12 weeks were ending, Malia was down 30lbs. Over the next six months she would lose another 30lbs. She was STRONG. And she was smiling. Everyone noticed her. there was a difference. She was glowing. Radiating. Sure, she still had more fat to lose, more muscle to gain, more areas to heal. But she shifted. Out of the old and into a new way of being. It was no longer simply \"needing\" or \"wanting\" to change, now Malia knew that she MUST change. And that changed everything. She had left behind what was holding herself back all those years, what was no longer serving her. And now, she must never go back.

She had awoken her Warrior Goddess. Her Divine Badass. Her Rebel Heart.""","""
<div class="sectionTitle">Rebel</div>
<div class="project"><div class="projectTitle">Rebellion Body</div><div class="projectDesc"><p><a class="ext" href="https://rebellionbody.com/" target="_blank" rel="noopener">rebellionbody.com</a></p></div></div>
""")
}
for name, html in pages.items():
    Path(name).write_text(html)
